modLoader = "javafml"
loaderVersion = "[${forgeDependencyVersion},)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "hextended"
version = "${version}"
displayName = "Hextended Gear"
logoFile = "icon.png"
authors = "just_laniakea"
description = '''
Bolsters your stick collection with some nice-looking staves with extra casting properties!
'''

[[dependencies.hextended]]
modId = "forge"
mandatory = true
versionRange = "[${forgeDependencyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hextended]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hextended]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.hextended]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.10.3,)"
ordering = "NONE"
side = "BOTH"
