modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "lanishextendedstaves"
version = "${version}"
displayName = "Hextended Staves"
logoFile = "icon.png"
authors = "just_laniakea"
description = '''
Bolsters your stick collection with some nice-looking staves with extra casting properties!
'''

[[dependencies.lanishextendedstaves]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lanishextendedstaves]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lanishextendedstaves]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.85,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lanishextendedstaves]]
modId = "hexcasting"
mandatory = true
versionRange = "[0.10.3,)"
ordering = "NONE"
side = "BOTH"
