modLoader = "javafml"
loaderVersion = "[${forgeDependencyVersion},)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "lanishextendedstaves"
version = "1.0.1"
displayName = "Hextended Staves"
logoFile = "icon.png"
authors = "just_laniakea"
description = '''
Bolsters your stick collection with some nice-looking staves with extra casting properties!
'''

[[dependencies.lanishextendedstaves]]
modId = "forge"
mandatory = true
versionRange = "[${forgeDependencyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lanishextendedstaves]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lanishextendedstaves]]
modId = "architectury"
mandatory = true
versionRange = "[${architecturyVersion},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.lanishextendedstaves]]
modId = "hexcasting"
mandatory = true
versionRange = "{${hexcastingVersion},)"
ordering = "NONE"
side = "BOTH"
