# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
# https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.0.4
_src_path: gh:object-Object/hexdummy
author: just_laniakea
capitalize_platforms: false
classname: LanisHextendedStaves
default_branch: main
description: Bolsters your stick collection with some nice-looking staves with extra
    casting properties!
display_name: Hextended Gear
github_repo: hextended-staves
hexcasting_version: 0.11.2
homepage_url: https://abilliontrillionstars.github.io/hextended-staves
initial_mod_version: 1.0.1
java_version: 17
license: MIT
mappings_name: Mojmap
modid: hextended
package: abilliontrillionstars.hextended
sources_url: github.com/abilliontrillionstars/hextended-staves
