# Changes here will be overwritten by Copier. NEVER EDIT MANUALLY
# See: https://copier.readthedocs.io/en/stable/configuring/#the-copier-answersyml-file
_commit: v0.1.11
_src_path: gh:hexdoc-dev/hexdoc-hexcasting-template
author: just_laniakea
book_id: lanishextendedstaves:lanishextendedstavesbook
default_branch: main
github_repo: hextended-staves
gradle_mod_version_key: modVersion
hexdoc_mod_plugin_classname: LanisHextendedStavesModPlugin
hexdoc_plugin_classname: LanisHextendedStavesPlugin
java_lang:
    ext: java
    src: java
java_package: abilliontrillionstars/lanishextendedstaves
mod_display_name: Hextended Staves
modid: lanishextendedstaves
multiloader: true
package_export_root: doc/src/hexdoc_lanishextendedstaves/_export
package_name: hexdoc-lanishextendedstaves
package_slug: hexdoc_lanishextendedstaves
package_src: doc/src/hexdoc_lanishextendedstaves
pages_url: https://abilliontrillionstars.github.io/hextended-staves/
pattern_regex:
    per_world_value: registerPerWorld
    regex: (?P<is_per_world>register|registerPerWorld)\(HexPattern\.fromAngles\("(?P<signature>[qweasd]+)",\s*HexDir\.(?P<startdir>\w+)\),\s*"(?P<name>[^"]+)"?
pattern_registry: registry/LanisHextendedStavesPatternRegistry.java
