modid = "lanishextendedstaves"
book = "lanishextendedstaves:lanishextendedstavesbook"
default_lang = "en_us"
default_branch = "main"

resource_dirs = [  # top takes priority
    "resources",
    "{_common.src}/main/resources",
    { path="{^_common.src}/generated/resources", required=false },
    "{_fabric.src}/main/resources",
    { path="{^_fabric.src}/generated/resources", required=false },
    "{_forge.src}/main/resources",
    { path="{^_forge.src}/generated/resources", required=false },
    { modid="hexcasting" },
    { modid="minecraft" },
    { modid="hexdoc" },
    { modid="hexgloop" },
]
export_dir = "src/hexdoc_lanishextendedstaves/_export/generated"

[template]
icon = "icon.png"
include = [
    "lanishextendedstaves",
    "hexcasting",
    "hexdoc",
]

[template.args]
mod_name = "Hextended Staves"
author = "abilliontrillionstars"
show_landing_text = false

[extra.hexcasting]
# regexes for parsing pattern registry files - try running copier update and picking a different regex if your patterns aren't loading
# NOTE: "!Raw" means "don't apply variable interpolation to this value"
pattern_stubs = []


[textures]
# make hexdoc ignore something that doesn't have a texture (if it's present in the book, it'll be given the purple-black checker)
missing = [
    "lanishextendedstaves:extended_staff",
    "lanishextendedstaves:livingwood_staff",
    "hexcasting:mangrove_staff"
]

[textures.override]
# use when you want hexdoc to sub in a texture for something when serving
# ex: "hexgloop:fake_spellbook_for_rei" = { texture = "hexcasting:textures/item/spellbook_empty.png" }


# platforms

[_common]
src = "../common/src"
package = "{src}/main/java/abilliontrillionstars/lanishextendedstaves"

[_fabric]
src = "../fabric/src"
package = "{src}/main/java/abilliontrillionstars/lanishextendedstaves/fabric"

[_forge]
src = "../forge/src"
package = "{src}/main/java/abilliontrillionstars/lanishextendedstaves/forge"
